### ISSUE TITLE
Python doc blocks are yellow with Nord color scheme

### ISSUE THREAD

**Issue by janbuchar** [ChristianChiarulli/nvcode-color-schemes.vim#37]
I have neovim nightly and the most up to date version of `nvim-treesitter` and this plugin. For some reason, Python doc blocks are highlighted in yellow (`#ffff00`), which I'm pretty sure isn't intended. Otherwise, everything seems to be highlighted correctly.

What can I do to fix this, and what other information should I provide?

I'd wager the problem is in these lines: https://github.com/ChristianChiarulli/nvcode-color-schemes.vim/blob/master/nord.yml#L192-L199

**Comment by pesader** [comment]
You can overwrite it locally with this (after you load the plugin):

```vim
" Treesitter
highlight! TSText guifg='#A3BE8C'
highlight! TSStrong guifg='#A3BE8C'
highlight! TSEmphasis guifg='#A3BE8C'
highlight! TSUnderline guifg='#A3BE8C'
highlight! TSTitle guifg='#A3BE8C'
highlight! TSLiteral guifg='#A3BE8C'
highlight! TSURI guifg='#A3BE8C'
```

This will give you the green color you'd expect from nordic python docstrings :)
The nordic yellow color is #EBCB8B, in case you want to stick with yellow.

**Comment by cristian-heredia** [comment]
Should be fixed in this [PR](https://github.com/ChristianChiarulli/nvcode-color-schemes.vim/pull/42) Some of Treesitter highlight groups are still in a work in progress.

**Comment by janbuchar** [comment]
Confirming this is fixed.
