### ISSUE TITLE
Namespace color in metanoia colorscheme

### ISSUE THREAD

**Issue by nkoturovic** [ChristianChiarulli/nvcode-color-schemes.vim#53]
Namespace (Magenta) color looks odd in metanoia colorscheme

![https://i.postimg.cc/gjKYNckk/meta-fix.png](https://i.postimg.cc/gjKYNckk/meta-fix.png)

@sinuheshinbr 
I think this vibrant magenta color is probably not intended to be like this??

**Comment by sinuheshinbr** [comment]
Yeah, not really. Not sure what happened there, I tried to reproduce here but std is showing as TSNamespace. You got treesitter configured with cpp lang server?

**Comment by nkoturovic** [comment]
@sinuheshinbr
Yeah, it seems that it is actually showing TSNamespace color.

![https://i.ibb.co/Lz6jcgM/metanoia-ns-color.png](https://i.ibb.co/Lz6jcgM/metanoia-ns-color.png)

**Note:** There are some other fields in `metanoia.yml` that use HEX codes directly (also very vibrant colors), maybe you've missed those? 

**btw, I like this colorscheme it looks very nice**

**Comment by sinuheshinbr** [comment]
Hey, my bad, TSNamespace was blue here, I probably changed it after the PR. The vibrant colors were groups that I did not encounter so they were left behind. I chose some random colors for them, but if you are using one of those HL groups and want to suggest any color that makes more sense just let me know! Already submitted a new PR with the updates.

**Comment by nkoturovic** [comment]
Nice, everything else looks great. I will use this updated version some time and if I encounter some inconsistency or get some improvement idea i will bring it up.

Closed: 4c7b42fadb
